
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automation-report-service
    ports:
      - "3036:3000"
    env_file:
      - .env
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://13.233.69.163:3100/loki/api/v1/push"
