services:
  report-service:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge