
services:
  report-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automation-report-service
    ports:
      - "${PORT:-3036}:${PORT:-3000}"
    env_file:
      - .env
    restart: always

