export const flowConfig: { [key: string]: string[] } = {
  default: [
    "search",
    "on_search",
    "search",
    "on_search",
    "select",
    "on_select",
    "init",
    "on_init",
    "confirm",
    "on_confirm",
  ],
  STATION_CODE_FLOW_CATALOG: ["search", "on_search"],
  STATION_CODE_FLOW_ORDER: [
    "search",
    "on_search",
    "select",
    "on_select",
    "init",
    "on_init",
    "confirm",
    "on_confirm",
    "status",
    "on_status",
  ],
  USER_CANCEL_FLOW: [
    "search",
    "on_search",
    "select",
    "on_select",
    "init",
    "on_init",
    "confirm",
    "on_confirm",
    "cancel",
    "on_cancel",
    "cancel",
    "on_cancel",
  ],
  TECHNICAL_CANCEL_FLOW: [
    "search",
    "on_search",
    "select",
    "on_select",
    "init",
    "on_init",
    "confirm",
    "status",
    "on_status",
    "cancel",
    "on_cancel",
  ],
  DELAYED_CANCELLATION_FLOW: [
    "search",
    "on_search",
    "select",
    "on_select",
    "init",
    "on_init",
    "confirm",
    "on_confirm",
    "cancel",
    "on_cancel",
    "on_status",
  ],
  DELAYED_CANCEllATION_FLOW: [
    "search",
    "on_search",
    "select",
    "on_select",
    "init",
    "on_init",
    "confirm",
    "on_confirm",
    "cancel",
    "on_cancel",
    "on_update",
  ],
};
