export const flowConfig: { [key: string]: string[] } = {
    default: [
      "search",
      "on_search",
      "search",
      "on_search",
      "select",
      "on_select",
      "init",
      "on_init",
      "confirm",
      "on_confirm",
    ],
    STATION_CODE_FLOW: [
        "search",
        "on_search",
        "search",
        "on_search",
        "select",
        "on_select",
        "init",
        "on_init",
        "confirm",
        "on_confirm",
        "status",
        "on_status"
    ],
    CANCEL_FLOW: [
      "search",
      "on_search",
      "search",
      "on_search",
      "select",
      "on_select",
      "init",
      "on_init",
      "confirm",
      "on_confirm",
      "cancel",
      "on_cancel"
  ],
  };