domains:
  ONDC:TRV11:
    versions:
      "2.0.1":
        flows:
          STATION_CODE_FLOW_CATALOG:
            - search
            - on_search

          STATION_CODE_FLOW_ORDER:
            - search
            - on_search
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - status
            - on_status

          USER_CANCEL_FLOW:
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - cancel
            - on_cancel
            - cancel
            - on_cancel

          TECHNICAL_CANCELLATION_FLOW:
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - status
            - on_status
            - cancel
            - on_cancel

          DELAYED_CANCELLATION_FLOW_REJECTED:
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - cancel
            - on_cancel
            - on_status

          DELAYED_CANCELLATION_FLOW_ACCEPTED:
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - cancel
            - on_cancel
            - on_update
        optional_flows:
          - DELAYED_CANCELLATION_FLOW_REJECTED
        validationModules: "../validations/trv11/validator#validate"
      "2.0.0":
        flows:
          STATION_CODE_FLOW_CATALOG:
            - search
            - on_search

          STATION_CODE_FLOW_ORDER:
            - search
            - on_search
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - status
            - on_status

          USER_CANCEL_FLOW:
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - cancel
            - on_cancel
            - cancel
            - on_cancel

          TECHNICAL_CANCELLATION_FLOW:
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - status
            - on_status
            - cancel
            - on_cancel

          DELAYED_CANCELLATION_FLOW_REJECTED:
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - cancel
            - on_cancel
            - on_status

          DELAYED_CANCELLATION_FLOW_ACCEPTED:
            - search
            - on_search
            - select
            - on_select
            - init
            - on_init
            - confirm
            - on_confirm
            - cancel
            - on_cancel
            - on_update
        optional_flows:
          - DELAYED_CANCELLATION_FLOW_REJECTED
        validationModules: "../validations/trv11/validator#validate"