save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  order_id: "$.message.order.id"
  order_status: "$.message.order.status"
  provider: "$.message.order.provider"
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  quote: "$.message.order.quote"
  quote_breakup: "$.message.order.quote.breakup[*]"
  payments: "$.message.order.payments[*]"
  tags: "$.message.order.tags[*]"
  billing: "$.message.order.billing"
  created_at: "$.message.order.created_at"
  updated_at: "$.message.order.updated_at"


