save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  order: "$.message.order"
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  provider: "$.message.order.provider"

